sonar.projectKey=lollipop-dummy-service
sonar.projectName=Lollipop Dummy Service
sonar.projectVersion=1.0.0

# Source and test paths
sonar.sources=src/app
sonar.tests=src/test

# Encoding
sonar.sourceEncoding=UTF-8

# Language
sonar.language=js

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions
sonar.exclusions=src/test/**,node_modules/**,coverage/**

# Test exclusions
sonar.test.exclusions=src/test/**

# Coverage exclusions
sonar.coverage.exclusions=src/test/**