/**
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


const CIECertData = require('./CIECertData');
const SPIDCertData = require('./SPIDCertData');

/**
 * The CertData model module.
 * @module model/CertData
 * @version 2022-09-06T20:08:39Z
 */
class CertData {
    /**
     * Constructs a new <code>CertData</code>.
     * @alias module:model/CertData
     * @param {(module:model/CIECertData|module:model/SPIDCertData)} instance The actual instance to initialize CertData.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }

        this.actualInstance = instance;

    }

    /**
     * Constructs a <code>CertData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CertData} obj Optional instance to populate.
     * @return {module:model/CertData} The populated <code>CertData</code> instance.
     */
    static constructFromObject(data, obj) {
        return new CertData(data);
    }

    /**
     * Gets the actual instance, which can be <code>CIECertData</code>, <code>SPIDCertData</code>.
     * @return {(module:model/CIECertData|module:model/SPIDCertData)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>CIECertData</code>, <code>SPIDCertData</code>.
     * @param {(module:model/CIECertData|module:model/SPIDCertData)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = CertData.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of CertData from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/CertData} An instance of CertData.
     */
    static fromJSON = function(json_string){
        return CertData.constructFromObject(JSON.parse(json_string));
    }
}

CertData.OneOf = ["CIECertData", "SPIDCertData"];


module.exports = CertData;
