/**
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

/**
 * The SPIDCertData model module.
 * @module model/SPIDCertData
 * @version 2022-09-06T20:08:39Z
 */
class SPIDCertData {
    /**
     * Constructs a new <code>SPIDCertData</code>.
     * @alias module:model/SPIDCertData
     */
    constructor() { 
        
        SPIDCertData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SPIDCertData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SPIDCertData} obj Optional instance to populate.
     * @return {module:model/SPIDCertData} The populated <code>SPIDCertData</code> instance.
     */
/*    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SPIDCertData();

            if (data.hasOwnProperty('entitiesDescriptor')) {
                obj['entitiesDescriptor'] = SPIDCertDataEntitiesDescriptor.constructFromObject(data['entitiesDescriptor']);
            }
        }
        return obj;
    }
*/
    /**
     * Validates the JSON data with respect to <code>SPIDCertData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SPIDCertData</code>.
     */
/*    static validateJSON(data) {
        // validate the optional field `entitiesDescriptor`
        if (data['entitiesDescriptor']) { // data not null
          SPIDCertDataEntitiesDescriptor.validateJSON(data['entitiesDescriptor']);
        }

        return true;
    }
*/

}



/**
 * @member {module:model/SPIDCertDataEntitiesDescriptor} entitiesDescriptor
 */
///SPIDCertData.prototype['entitiesDescriptor'] = undefined;


module.exports = SPIDCertData;
