AWSTemplateFormatVersion: 2010-09-09
Description: 'Example microservice deploy'

Parameters:
  ProjectName:
    Type: String
    Description: 'Usually pn can be pnXYZ where XYZ are the feature number, useful to create
      experimental environments without crash official development environment'

  LambdasBucketName:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'
  
  LambdaZipVersionId1:
    Type: String
    Description: 'First lambda zip file S3 VersionId'
  LambdaZipVersionId2:
    Type: String
    Description: 'Second lambda zip file S3 VersionId'
  LambdaZipVersionId3:
    Type: String
    Description: 'Third lambda zip file S3 VersionId'

  MicroserviceNumber:
    Type: Number
    Description: 'Disambiguation useful for load balancer rules'

  TemplateBucketBaseUrl:
    Type: String
    Description: 'The S3 bucket from which to fetch the templates used by this stack.'

  
  SubnetsIds:
    Type: String
    Description: 'subnets ids comma separated list. Where to deploy the microservice'

  VpcId:
    Type: String
    Description: 'VpcId where the microservice is going to be deployed'

  
Resources:

  # Internal queues
  JustAResourceQueue:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateBucketBaseUrl}/fragments/sqs-queue.yaml"
      Parameters:
        QueueName: !Sub '${ProjectName}-just_a_queue-${LambdaZipVersionId3}'
        DelaySeconds: 1