/**
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

const ApiClient = require("../ApiClient");
const CertData = require("../model/CertData");  //.default;

/**
* Default service.
* @module api/DefaultApi
* @version 2022-09-06T20:08:39Z
*/
class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * @param {idpClientConfig}
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient, idpClientConfig) {
        this.apiClient = apiClient || ApiClient.instance;
        this.idpClientConfig = idpClientConfig;
    }


    /**
     * Callback function to receive the result of the idpKeysCieGet operation.
     * @callback module:api/DefaultApi~idpKeysCieGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/DefaultApi~idpKeysCieGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    idpKeysCieGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        //'/idp-keys/cie', 'GET',
        this.idpClientConfig.IDP_KEYS_CIE_ENDPOINT, 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the idpKeysCieTagGet operation.
     * @callback module:api/DefaultApi~idpKeysCieTagGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CertData} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} tag 
     * @param {module:api/DefaultApi~idpKeysCieTagGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CertData}
     */
    idpKeysCieTagGet(tag, callback) {
      let postBody = null;
      // verify the required parameter 'tag' is set
      if (tag === undefined || tag === null) {
        throw new Error("Missing the required parameter 'tag' when calling idpKeysCieTagGet");
      }

      let pathParams = {
        'tag': tag
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/xml', 'application/json'];
      let returnType = CertData;
      return this.apiClient.callApi(
        //'/idp-keys/cie/{tag}', 'GET',
        this.idpClientConfig.IDP_KEYS_CIE_ENDPOINT+'/{tag}','GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the idpKeysSpidGet operation.
     * @callback module:api/DefaultApi~idpKeysSpidGetCallback
     * @param {String} error Error message, if any.
     * @param {Array.<String>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/DefaultApi~idpKeysSpidGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<String>}
     */
    idpKeysSpidGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ['String'];
      return this.apiClient.callApi(
        //'/idp-keys/spid', 'GET',
        this.idpClientConfig.IDP_KEYS_SPID_ENDPOINT,'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the idpKeysSpidTagGet operation.
     * @callback module:api/DefaultApi~idpKeysSpidTagGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/CertData} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} tag 
     * @param {module:api/DefaultApi~idpKeysSpidTagGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/CertData}
     */
    idpKeysSpidTagGet(tag, callback) {
      let postBody = null;
      // verify the required parameter 'tag' is set
      if (tag === undefined || tag === null) {
        throw new Error("Missing the required parameter 'tag' when calling idpKeysSpidTagGet");
      }

      let pathParams = {
        'tag': tag
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/xml', 'application/json'];
      let returnType = CertData;
      return this.apiClient.callApi(
        //'/idp-keys/spid/{tag}', 'GET',
        this.idpClientConfig.IDP_KEYS_SPID_ENDPOINT+'/{tag}','GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
module.exports = DefaultApi;