
        const ASSERTION_SPID_XML_WITH_VALID_ENTITY_ID_WITHOUT_CERT =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t<saml2:Issuer"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://posteid.poste.it</saml2:Issuer>"
                + "\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://posteid.poste.it\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";


        const ASSERTION_CIE_XML_WITH_VALID_ENTITY_ID_WITH_CERT =
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?><saml2p:Response"
                + " xmlns:saml2p=\"urn:oasis:names:tc:SAML:2.0:protocol\""
                + " Destination=\"https://app-backend.io.italia.it/assertionConsumerService\""
                + " ID=\"_de2ce675-f1e5-46fc-96ed-019803471175\""
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " IssueInstant=\"2023-02-28T16:27:26.400Z\" Version=\"2.0\">   <saml2:Assertion"
                + " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                + " ID=\"_6b9580aa-08b1-4f19-8fb6-8b670d070bad\""
                + " IssueInstant=\"2023-02-28T16:27:25.400Z\" Version=\"2.0\">\t<saml2:Issuer"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:entity\">https://idserver.servizicie.interno.gov.it/idp/profile/SAML2/POST/SSO</saml2:Issuer>"
                + "\t<saml2:Subject>\t\t\t<saml2:NameID"
                + " Format=\"urn:oasis:names:tc:SAML:2.0:nameid-format:transient\""
                + " NameQualifier=\"https://idserver.servizicie.interno.gov.it/idp/profile/SAML2/POST/SSO\">SPID-d4de186b-e103-4b39-8209-0bccc7b1acdd</saml2:NameID>"
                + "\t\t\t<saml2:SubjectConfirmation"
                + " Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">\t\t\t"
                + "\t<saml2:SubjectConfirmationData"
                + " InResponseTo=\"sha256-a7qE0Y0DyqeOFFREIQSLKfu5WlbckdxVXKFasfcI-Dg\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\""
                + " Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\" />\t\t"
                + "\t</saml2:SubjectConfirmation>\t\t</saml2:Subject>\t\t<saml2:Conditions"
                + " NotBefore=\"2023-02-28T16:27:25.400Z\""
                + " NotOnOrAfter=\"2023-02-28T16:28:25.400Z\">\t\t\t<saml2:AudienceRestriction>\t\t"
                + "\t\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>\t\t"
                + "\t</saml2:AudienceRestriction>\t\t</saml2:Conditions>\t"
                + "\t<saml2:AttributeStatement>\t\t\t<saml2:Attribute FriendlyName=\"Codice"
                + " fiscale\" Name=\"fiscalNumber\">\t\t\t\t<saml2:AttributeValue"
                + " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                + " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                + " xsi:type=\"xs:string\">TINIT-AAAAAA89S20I111X</saml2:AttributeValue>\t\t"
                + "\t</saml2:Attribute>\t\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion></saml2p:Response>";

    const ASSERTION_SPID_XML_WITH_VALID_ENTITY_ID_WITH_CERT =
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
                + "\t<saml2:Assertion"
                    +  " xmlns:saml2=\"urn:oasis:names:tc:SAML:2.0:assertion\""
                    +  " xmlns:xs=\"http://www.w3.org/2001/XMLSchema\""
                    +  " xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\""
                    +  " xmlns:ds=\"http://www.w3.org/2000/09/xmldsig#\""
                    +  " ID=\"_f43e1183-5c79-4d6f-99a3-57551410f92b\""
                    +  " IssueInstant=\"2025-11-04T11:50:34.570Z\""
                    +  " Version=\"2.0\">"
                    + "\t<saml2:Issuer>https://posteid.poste.it</saml2:Issuer>"
                    + "\t<saml2:Subject>"
                        + "\t<saml2:NameID Format=\"urn:oasis:names:tc:SAML:2.0:nameid:transient\">_781edb39-813f-42a1-b4f5-cf6d028a31e8</saml2:NameID>"
                        + "\t<saml2:SubjectConfirmation Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\">"
                            + "\t<saml2:SubjectConfirmationData"
                                + "\t InResponseTo=\"sha256-Iz4GEYGtznLdLyHrbtKEkzb6qSJpOkKvsOsCxgXkIhI\""
                                    + "\t NotOnOrAfter=\"2025-11-04T11:55:34.570Z\""
                                    + "\t Recipient=\"https://app-backend.io.italia.it/assertionConsumerService\"/>"
                        + "\t</saml2:SubjectConfirmation>"
                    + "\t</saml2:Subject>"
                    + "\t<saml2:Conditions NotBefore=\"2025-11-04T11:50:33.570Z\" NotOnOrAfter=\"2025-11-04T11:55:34.570Z\">"
                        + "\t<saml2:AudienceRestriction>"
                            + "\t<saml2:Audience>https://app-backend.io.italia.it</saml2:Audience>"
                        + "\t</saml2:AudienceRestriction>"
                    + "\t</saml2:Conditions>"
                    + "\t<saml2:AuthnStatement AuthnInstant=\"2025-11-04T11:50:33.570Z\">"
                        + "\t<saml2:AuthnContext>"
                            + "\t<saml2:AuthnContextClassRef>https://www.spid.gov.it/SpidL2</saml2:AuthnContextClassRef>"
                        + "\t</saml2:AuthnContext>"
                    + "\t</saml2:AuthnStatement>"
                    + "\t<saml2:AttributeStatement>"
                        + "\t<saml2:Attribute Name=\"email\">"
                            + "\t<saml2:AttributeValue xsi:type=\"xs:string\">albertino@gmail.com</saml2:AttributeValue>"
                        + "\t</saml2:Attribute>"
                        + "\t<saml2:Attribute Name=\"fiscalNumber\">"
                            + "\t<saml2:AttributeValue xsi:type=\"xs:string\">TINIT-AAAAAA00A00A000A</saml2:AttributeValue>"
                        + "\t</saml2:Attribute>"
                    + "\t</saml2:AttributeStatement>"
                + "\t</saml2:Assertion>";

module.exports = {
    ASSERTION_SPID_XML_WITH_VALID_ENTITY_ID_WITHOUT_CERT,
    ASSERTION_CIE_XML_WITH_VALID_ENTITY_ID_WITH_CERT,
    ASSERTION_SPID_XML_WITH_VALID_ENTITY_ID_WITH_CERT,
}