/**
 * Assertion Client
 * Client used to get the assertion from the identity provider
 *
 * The version of the OpenAPI document: $npm_package_version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient.js"
/**
 * The AssertionRef model module.
 * @module model/AssertionRef
 * @version $npm_package_version
 */
class AssertionRef {
    /**
     * Constructs a new <code>AssertionRef</code>.
     * @alias module:model/AssertionRef
     * @param {(module:model/String)} instance The actual instance to initialize AssertionRef.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            if (!/^(sha256-[A-Za-z0-9-_=]{1,44})$/.test(instance)) {
                throw new Error("Invalid string value. Must conform to /^(sha256-[A-Za-z0-9-_=]{1,44})$/. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            if (!/^(sha384-[A-Za-z0-9-_=]{1,66})$/.test(instance)) {
                throw new Error("Invalid string value. Must conform to /^(sha384-[A-Za-z0-9-_=]{1,66})$/. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            if (!/^(sha512-[A-Za-z0-9-_=]{1,88})$/.test(instance)) {
                throw new Error("Invalid string value. Must conform to /^(sha512-[A-Za-z0-9-_=]{1,88})$/. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `AssertionRef` with oneOf schemas String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `AssertionRef` with oneOf schemas String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>AssertionRef</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssertionRef} obj Optional instance to populate.
     * @return {module:model/AssertionRef} The populated <code>AssertionRef</code> instance.
     */
    static constructFromObject(data, obj) {
        return new AssertionRef(data);
    }

    /**
     * Gets the actual instance, which can be <code>String</code>.
     * @return {(module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>String</code>.
     * @param {(module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = AssertionRef.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of AssertionRef from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/AssertionRef} An instance of AssertionRef.
     */
    static fromJSON = function(json_string){
        return AssertionRef.constructFromObject(JSON.parse(json_string));
    }
}


AssertionRef.OneOf = ["String"];

AssertionRef.instance = new AssertionRef();

export default AssertionRef;
