/**
 * Assertion Client
 * Client used to get the assertion from the identity provider
 *
 * The version of the OpenAPI document: $npm_package_version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

const ApiClient = require('../ApiClient').default/**
* Enum class AssertionType.
* @enum {}
* @readonly
*/
class AssertionType {
    
    static SAML = "SAML";
    static OIDC = "OIDC";

    

    /**
    * Returns a <code>AssertionType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AssertionType} The enum <code>AssertionType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}
module.exports = AssertionType;