/**
 * Assertion Client
 * Client used to get the assertion from the identity provider
 *
 * The version of the OpenAPI document: $npm_package_version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient.js"
import OidcUserInfo from "./OidcUserInfo.js";
import SamlUserInfo from "./SamlUserInfo.js";

/**
 * The LCUserInfo model module.
 * @module model/LCUserInfo
 * @version $npm_package_version
 */
class LCUserInfo {
    /**
     * Constructs a new <code>LCUserInfo</code>.
     * @alias module:model/LCUserInfo
     * @param {(module:model/OidcUserInfo|module:model/SamlUserInfo)} instance The actual instance to initialize LCUserInfo.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (typeof instance === "SamlUserInfo") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                SamlUserInfo.validateJSON(instance); // throw an exception if no match
                // create SamlUserInfo from JS object
                this.actualInstance = SamlUserInfo.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into SamlUserInfo
            errorMessages.push("Failed to construct SamlUserInfo: " + err)
        }

        try {
            if (typeof instance === "OidcUserInfo") {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                OidcUserInfo.validateJSON(instance); // throw an exception if no match
                // create OidcUserInfo from JS object
                this.actualInstance = OidcUserInfo.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into OidcUserInfo
            errorMessages.push("Failed to construct OidcUserInfo: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `LCUserInfo` with oneOf schemas OidcUserInfo, SamlUserInfo. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `LCUserInfo` with oneOf schemas OidcUserInfo, SamlUserInfo. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>LCUserInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LCUserInfo} obj Optional instance to populate.
     * @return {module:model/LCUserInfo} The populated <code>LCUserInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        return new LCUserInfo(data);
    }

    /**
     * Gets the actual instance, which can be <code>OidcUserInfo</code>, <code>SamlUserInfo</code>.
     * @return {(module:model/OidcUserInfo|module:model/SamlUserInfo)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>OidcUserInfo</code>, <code>SamlUserInfo</code>.
     * @param {(module:model/OidcUserInfo|module:model/SamlUserInfo)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = LCUserInfo.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of LCUserInfo from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/LCUserInfo} An instance of LCUserInfo.
     */
    static fromJSON = function(json_string){
        return LCUserInfo.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * A string representation of a signed SPID/CIE response
 * @member {String} response_xml
 */
LCUserInfo.prototype['response_xml'] = undefined;

/**
 * A JWT representation of a signed SPID/CIE OIDC Idp
 * @member {String} id_token
 */
LCUserInfo.prototype['id_token'] = undefined;

/**
 * A JWT representation of a signed SPID/CIE OIDC Idp
 * @member {String} claims_token
 */
LCUserInfo.prototype['claims_token'] = undefined;


LCUserInfo.OneOf = ["OidcUserInfo", "SamlUserInfo"];

LCUserInfo.instance = new LCUserInfo();

export default LCUserInfo;

