/**
 * Assertion Client
 * Client used to get the assertion from the identity provider
 *
 * The version of the OpenAPI document: $npm_package_version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

const ApiClient = require('../ApiClient');
const LCUserInfo = require('./LCUserInfo');
/**
 * The OidcUserInfo model module.
 * @module model/OidcUserInfo
 * @version $npm_package_version
 */
class OidcUserInfo {
    /**
     * Constructs a new <code>OidcUserInfo</code>.
     * @alias module:model/OidcUserInfo
     * @param idToken {String} A JWT representation of a signed SPID/CIE OIDC Idp
     * @param claimsToken {String} A JWT representation of a signed SPID/CIE OIDC Idp
     */
    constructor(idToken, claimsToken) { 
        
        OidcUserInfo.initialize(this, idToken, claimsToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idToken, claimsToken) { 
        obj['id_token'] = idToken;
        obj['claims_token'] = claimsToken;
    }

    /**
     * Constructs a <code>OidcUserInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OidcUserInfo} obj Optional instance to populate.
     * @return {module:model/OidcUserInfo} The populated <code>OidcUserInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OidcUserInfo();

            if (data.hasOwnProperty('id_token')) {
                obj['id_token'] = ApiClient.convertToType(data['id_token'], 'String');
            }
            if (data.hasOwnProperty('claims_token')) {
                obj['claims_token'] = ApiClient.convertToType(data['claims_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OidcUserInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OidcUserInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OidcUserInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id_token'] && !(typeof data['id_token'] === 'string' || data['id_token'] instanceof String)) {
            throw new Error("Expected the field `id_token` to be a primitive type in the JSON string but got " + data['id_token']);
        }
        // ensure the json data is a string
        if (data['claims_token'] && !(typeof data['claims_token'] === 'string' || data['claims_token'] instanceof String)) {
            throw new Error("Expected the field `claims_token` to be a primitive type in the JSON string but got " + data['claims_token']);
        }

        return true;
    }


}

OidcUserInfo.RequiredProperties = ["id_token", "claims_token"];

/**
 * A JWT representation of a signed SPID/CIE OIDC Idp
 * @member {String} id_token
 */
OidcUserInfo.prototype['id_token'] = undefined;

/**
 * A JWT representation of a signed SPID/CIE OIDC Idp
 * @member {String} claims_token
 */
OidcUserInfo.prototype['claims_token'] = undefined;






module.exports=OidcUserInfo;
