/**
 * Assertion Client
 * Client used to get the assertion from the identity provider
 *
 * The version of the OpenAPI document: $npm_package_version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from "../ApiClient.js";
/**
 * The SamlUserInfo model module.
 * @module model/SamlUserInfo
 * @version $npm_package_version
 */
class SamlUserInfo {
    /**
     * Constructs a new <code>SamlUserInfo</code>.
     * @alias module:model/SamlUserInfo
     * @param responseXml {String} A string representation of a signed SPID/CIE response
     */
    constructor(responseXml) { 
        
        SamlUserInfo.initialize(this, responseXml);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, responseXml) { 
        obj['response_xml'] = responseXml;
    }

    /**
     * Constructs a <code>SamlUserInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SamlUserInfo} obj Optional instance to populate.
     * @return {module:model/SamlUserInfo} The populated <code>SamlUserInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SamlUserInfo();

            if (data.hasOwnProperty('response_xml')) {
                obj['response_xml'] = ApiClient.convertToType(data['response_xml'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SamlUserInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SamlUserInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SamlUserInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['response_xml'] && !(typeof data['response_xml'] === 'string' || data['response_xml'] instanceof String)) {
            throw new Error("Expected the field `response_xml` to be a primitive type in the JSON string but got " + data['response_xml']);
        }

        return true;
    }


}

SamlUserInfo.RequiredProperties = ["response_xml"];

/**
 * A string representation of a signed SPID/CIE response
 * @member {String} response_xml
 */
SamlUserInfo.prototype['response_xml'] = undefined;



export default SamlUserInfo;

