/**
 * Assertion Client
 * Client used to get the assertion from the identity provider
 *
 * The version of the OpenAPI document: $npm_package_version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient.js";
import AssertionRef from "../model/AssertionRef.js";
import LCUserInfo from "../model/LCUserInfo.js";
import ProblemJson from "../model/ProblemJson.js";

/**
* Default service.
* @module api/DefaultApi
* @version $npm_package_version
*/
class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the getAssertion operation.
     * @callback module:api/DefaultApi~getAssertionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/LCUserInfo} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Assertion related to a given assertion ref
     * @param {module:model/AssertionRef} assertionRef 
     * @param {String} xPagopaLollipopAuth 
     * @param {module:api/DefaultApi~getAssertionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/LCUserInfo}
     */
    getAssertion(assertionRef, xPagopaLollipopAuth, callback) {
      let postBody = null;
      // verify the required parameter 'assertionRef' is set
      if (assertionRef === undefined || assertionRef === null) {
        throw new Error("Missing the required parameter 'assertionRef' when calling getAssertion");
      }
      // verify the required parameter 'xPagopaLollipopAuth' is set
      if (xPagopaLollipopAuth === undefined || xPagopaLollipopAuth === null) {
        throw new Error("Missing the required parameter 'xPagopaLollipopAuth' when calling getAssertion");
      }

      let pathParams = {
        'assertion_ref': assertionRef
      };
      let queryParams = {
      };
      let headerParams = {
        'x-pagopa-lollipop-auth': xPagopaLollipopAuth
      };
      let formParams = {
      };

      let authNames = ['ApiKeyAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = LCUserInfo;
      return this.apiClient.callApi(
        '/assertions/{assertion_ref}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
export default DefaultApi;