/**
 * Assertion Client
 * Client used to get the assertion from the identity provider
 *
 * The version of the OpenAPI document: $npm_package_version
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


const ApiClient = require('./ApiClient')
const AssertionRef =require( './model/AssertionRef');
const AssertionType =require( './model/AssertionType');
const LCUserInfo = require( './model/LCUserInfo');
const OidcUserInfo = require( './model/OidcUserInfo');
const ProblemJson= require ('./model/ProblemJson');
const SamlUserInfo = require( './model/SamlUserInfo');
const DefaultApi = require( './api/DefaultApi');


/**
* Client used to get the assertion from the identity provider.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var AssertionClient = require('index'); // See note below*.
* var xxxSvc = new AssertionClient.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new AssertionClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new AssertionClient.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new AssertionClient.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version $npm_package_version
*/

module.exports = {
    ApiClient,
    AssertionRef,
    AssertionType,
    LCUserInfo,
    OidcUserInfo,
    ProblemJson,
    SamlUserInfo,
    DefaultApi
}