// codici di errore di validazione della richiesta
const VALIDATION_ERROR_CODES = {
  MISSING_PUBLIC_KEY: "MISSING_PUBLIC_KEY",
  INVALID_PUBLIC_KEY: "INVALID_PUBLIC_KEY",
  MISSING_USER_ID: "MISSING_USER_ID",
  INVALID_USER_ID: "INVALID_USER_ID",
  MISSING_PUBLIC_KEY_ERROR: "MISSING_PUBLIC_KEY",
  INVALID_PUBLIC_KEY_ERROR: "INVALID_PUBLIC_KEY",
  MISSING_ASSERTION_TYPE_ERROR: "MISSING_ASSERTION_TYPE",
  INVALID_ASSERTION_TYPE_ERROR: "INVALID_ASSERTION_TYPE",
  MISSING_ASSERTION_REF_ERROR: "MISSING_ASSERTION_REF",
  INVALID_ASSERTION_REF_ERROR: "INVALID_ASSERTION_REF",
  MISSING_AUTH_JWT: "MISSING_AUTH_JWT",
  INVALID_AUTH_JWT: "INVALID_AUTH_JWT",
  MISSING_ORIGINAL_METHOD: "MISSING_ORIGINAL_METHOD",
  INVALID_ORIGINAL_METHOD: "INVALID_ORIGINAL_METHOD",
  UNEXPECTED_ORIGINAL_METHOD: "UNEXPECTED_ORIGINAL_METHOD",
  MISSING_ORIGINAL_URL: "MISSING_ORIGINAL_URL",
  INVALID_ORIGINAL_URL: "INVALID_ORIGINAL_URL",
  UNEXPECTED_ORIGINAL_URL: "UNEXPECTED_ORIGINAL_URL",
  MISSING_SIGNATURE_INPUT: "MISSING_SIGNATURE_INPUT",
  INVALID_SIGNATURE_INPUT: "INVALID_SIGNATURE_INPUT",
  MISSING_SIGNATURE: "MISSING_SIGNATURE",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
};

//codici di errore della verifica http
const VERIFY_HTTP_ERROR_CODES = {
    INVALID_SIGNATURE: "INVALID_SIGNATURE",
    INVALID_SIGNATURE_NUMBER: "INVALID_SIGNATURE_NUMBER",
    INVALID_JWK: "INVALID_JWK",
    INVALID_SIGNATURE_ALG: "INVALID_SIGNATURE_ALG",
    UNSUPPORTED_KEY_TYPE: "UNSUPPORTED_KEY_TYPE",
    UNSUPPORTED_ALG: "UNSUPPORTED_ALG"

}

module.exports = {
    VALIDATION_ERROR_CODES,
    VERIFY_HTTP_ERROR_CODES
}