// codici di errore per le validazioni
const VALIDATION_ERROR_CODES = {
    MISSING_PUBLIC_KEY: "MISSING_PUBLIC_KEY",
    INVALID_PUBLIC_KEY: "INVALID_PUBLIC_KEY",
    INVALID_ASSERTION_PERIOD: "INVALID_ASSERTION_PERIOD",
    MISSING_USER_ID: "MISSING_USER_ID",
    INVALID_USER_ID: "INVALID_USER_ID",
    MISSING_PUBLIC_KEY_ERROR: "MISSING_PUBLIC_KEY",
    INVALID_PUBLIC_KEY_ERROR: "INVALID_PUBLIC_KEY",
    MISSING_ASSERTION_TYPE_ERROR: "MISSING_ASSERTION_TYPE",
    INVALID_ASSERTION_TYPE_ERROR: "INVALID_ASSERTION_TYPE",
    MISSING_ASSERTION_REF_ERROR: "MISSING_ASSERTION_REF",
    INVALID_ASSERTION_REF_ERROR: "INVALID_ASSERTION_REF",
    MISSING_AUTH_JWT: "MISSING_AUTH_JWT",
    INVALID_AUTH_JWT: "INVALID_AUTH_JWT",
    MISSING_ORIGINAL_METHOD: "MISSING_ORIGINAL_METHOD",
    INVALID_ORIGINAL_METHOD: "INVALID_ORIGINAL_METHOD",
    UNEXPECTED_ORIGINAL_METHOD: "UNEXPECTED_ORIGINAL_METHOD",
    MISSING_ORIGINAL_URL: "MISSING_ORIGINAL_URL",
    INVALID_ORIGINAL_URL: "INVALID_ORIGINAL_URL",
    UNEXPECTED_ORIGINAL_URL: "UNEXPECTED_ORIGINAL_URL",
    MISSING_SIGNATURE_INPUT: "MISSING_SIGNATURE_INPUT",
    INVALID_SIGNATURE_INPUT: "INVALID_SIGNATURE_INPUT",
    MISSING_SIGNATURE: "MISSING_SIGNATURE",
    INVALID_SIGNATURE: "INVALID_SIGNATURE",
    ERROR_PARSING_ASSERTION_NOT_BEFORE_DATE: "ERROR_PARSING_ASSERTION_NOT_BEFORE_DATE",
    ERROR_PARSING_ASSERTION_DATE: "ERROR_PARSING_ASSERTION_DATE",
    NOTBEFORE_NOTVALID_DATE: "NOTBEFORE_NOTVALID_DATE",
    IN_RESPONSE_TO_FIELD_NOT_FOUND: "IN_RESPONSE_TO_FIELD_NOT_FOUND",
    IN_RESPONSE_TO_EMPTY_OR_INVALID: "IN_RESPONSE_TO_EMPTY_OR_INVALID",
    IN_RESPONSE_TO_ALGORITHM_NOT_VALID: "IN_RESPONSE_TO_ALGORITHM_NOT_VALID",
    INVALID_PUBLIC_KEY: "INVALID_PUBLIC_KEY",
    NAME_NOT_FOUND: "NAME_NOT_FOUND",
    SURNAME_NOT_FOUND: "SURNAME_NOT_FOUND",
    IDP_CERT_DATA_NOT_FOUND: "IDP_CERT_DATA_NOT_FOUND",
    GENERIC_ERROR: "GENERIC_ERROR",
    MISSING_ASSERTION_SIGNATURE: "MISSING_ASSERTION_SIGNATURE",
    INVALID_ASSERTION_SIGNATURE: "INVALID_ASSERTION_SIGNATURE",
    ERROR_PARSING_ASSERTION: "ERROR_PARSING_ASSERTION",
};

const ASSERTION_ERROR_CODES = {
    OIDC_ASSERTION_TYPE_NOT_SUPPORTED: "OIDC_TYPE_NOT_SUPPORTED",
    SAML_ASSERTION_NOT_FOUND: "SAML_ASSERTION_NOT_FOUND",
    ERROR_PARSING_ASSERTION: "ERROR_PARSING_ASSERTION",
}
//codici di errore della verifica http
const VERIFY_HTTP_ERROR_CODES = {
    INVALID_SIGNATURE: "INVALID_SIGNATURE",
    INVALID_SIGNATURE_NUMBER: "INVALID_SIGNATURE_NUMBER",
    INVALID_JWK: "INVALID_JWK",
    INVALID_SIGNATURE_ALG: "INVALID_SIGNATURE_ALG",
    UNSUPPORTED_KEY_TYPE: "UNSUPPORTED_KEY_TYPE",
    UNSUPPORTED_ALG: "UNSUPPORTED_ALG"

}
export { VALIDATION_ERROR_CODES,
    ASSERTION_ERROR_CODES,
    VERIFY_HTTP_ERROR_CODES }