// codici di errore
const VALIDATION_ERROR_CODES = {
  MISSING_PUBLIC_KEY: "MISSING_PUBLIC_KEY",
  INVALID_PUBLIC_KEY: "INVALID_PUBLIC_KEY",
  MISSING_USER_ID: "MISSING_USER_ID",
  INVALID_USER_ID: "INVALID_USER_ID",
  MISSING_PUBLIC_KEY_ERROR: "MISSING_PUBLIC_KEY",
  INVALID_PUBLIC_KEY_ERROR: "INVALID_PUBLIC_KEY",
  MISSING_ASSERTION_TYPE_ERROR: "MISSING_ASSERTION_TYPE",
  INVALID_ASSERTION_TYPE_ERROR: "INVALID_ASSERTION_TYPE",
  MISSING_ASSERTION_REF_ERROR: "MISSING_ASSERTION_REF",
  INVALID_ASSERTION_REF_ERROR: "INVALID_ASSERTION_REF",
  MISSING_AUTH_JWT: "MISSING_AUTH_JWT",
  INVALID_AUTH_JWT: "INVALID_AUTH_JWT",
};

//algoritmi predefiniti da usare in base al tipo di chiave (kty): in chiaro perchè importJWK non fa il parse del campo alg
const DEAFULT_ALG_BY_KTY = {
  EC: 'ES256',
  RSA: 'RS256',
};

const USER_ID_REGEX = /^[A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST][0-9LMNPQRSTUV]{2}[A-Z][0-9LMNPQRSTUV]{3}[A-Z]$/;

const AssertionRefAlgorithms = {
  SHA256: { pattern: /^sha256-[A-Za-z0-9_-]{44}$/ },
  SHA384: { pattern: /^sha384-[A-Za-z0-9_-]{66}$/ },
  SHA512: { pattern: /^sha512-[A-Za-z0-9_-]{86}$/ },
};

const COMPATIBLE_ASSERTION_TYPES=[
    "SAML"
];


module.exports = {
  VALIDATION_ERROR_CODES,
  DEAFULT_ALG_BY_KTY,
  USER_ID_REGEX,
  DEAFULT_ALG_BY_KTY,
  COMPATIBLE_ASSERTION_TYPES,
  AssertionRefAlgorithms
};
