// codici di errore
const VALIDATION_ERROR_CODES = {
  MISSING_PUBLIC_KEY: "MISSING_PUBLIC_KEY",
  INVALID_PUBLIC_KEY: "INVALID_PUBLIC_KEY",
  MISSING_ORIGINAL_METHOD: "MISSING_ORIGINAL_METHOD",
  INVALID_ORIGINAL_METHOD: "INVALID_ORIGINAL_METHOD",
  UNEXPECTED_ORIGINAL_METHOD: "UNEXPECTED_ORIGINAL_METHOD",
};

//algoritmi predefiniti da usare in base al tipo di chiave (kty): in chiaro perchè importJWK non fa il parse del campo alg
const DEAFULT_ALG_BY_KTY = {
  EC: 'ES256',
  RSA: 'RS256',
};

const EXPECTED_FIRST_LC_ORIGINAL_METHOD = "POST;GET";

const LOLLIPOP_REQUEST_METHOD = {
    GET: "GET",
    POST: "POST",
    PUT: "PUT",
    PATCH: "PATCH",
    DELETE: "DELETE",
};

module.exports = {
  VALIDATION_ERROR_CODES,
  DEAFULT_ALG_BY_KTY,
  LOLLIPOP_REQUEST_METHOD,
  EXPECTED_FIRST_LC_ORIGINAL_METHOD,
};
