/**
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

/**
 * The CIECertData model module.
 * @module model/CIECertData
 * @version 2022-09-06T20:08:39Z
 */
class CIECertData {
    /**
     * Constructs a new <code>CIECertData</code>.
     * @alias module:model/CIECertData
     */
    constructor() { 
        
        CIECertData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }


}



export default CIECertData;
