/**
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

const ApiClient = require('../ApiClient');

/**
 * The EntityDescriptor model module.
 * @module model/EntityDescriptor
 * @version 2022-09-06T20:08:39Z
 */
class EntityDescriptor {
    /**
     * Constructs a new <code>EntityDescriptor</code>.
     * @alias module:model/EntityDescriptor
     * @param entityID {String} 
     */
    constructor(entityID) { 
        
        EntityDescriptor.initialize(this, entityID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, entityID) { 
        obj['entityID'] = entityID;
    }

    /**
     * Constructs a <code>EntityDescriptor</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityDescriptor} obj Optional instance to populate.
     * @return {module:model/EntityDescriptor} The populated <code>EntityDescriptor</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityDescriptor();

            if (data.hasOwnProperty('entityID')) {
                obj['entityID'] = ApiClient.convertToType(data['entityID'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EntityDescriptor</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EntityDescriptor</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EntityDescriptor.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['entityID'] && !(typeof data['entityID'] === 'string' || data['entityID'] instanceof String)) {
            throw new Error("Expected the field `entityID` to be a primitive type in the JSON string but got " + data['entityID']);
        }

        return true;
    }


}

EntityDescriptor.RequiredProperties = ["entityID"];

/**
 * @member {String} entityID
 */
EntityDescriptor.prototype['entityID'] = undefined;


module.exports = EntityDescriptor;

