/**
 * identity-services
 * Client used to retrieve the public keys from the identity provider
 *
 * The version of the OpenAPI document: 2022-09-06T20:08:39Z
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

/**
 * The SPIDCertData model module.
 * @module model/SPIDCertData
 * @version 2022-09-06T20:08:39Z
 */
class SPIDCertData {
    /**
     * Constructs a new <code>SPIDCertData</code>.
     * @alias module:model/SPIDCertData
     */
    constructor() { 
        
        SPIDCertData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }


}

module.exports = SPIDCertData;
