// Validation error codes
const VALIDATION_ERROR_CODES = {
  MISSING_PUBLIC_KEY: "MISSING_PUBLIC_KEY",
  INVALID_PUBLIC_KEY: "INVALID_PUBLIC_KEY",
  INVALID_ASSERTION_PERIOD: "PERIOD_VALIDATION_ERROR",
  MISSING_USER_ID: "MISSING_USER_ID",
  INVALID_USER_ID: "USER_ID_VALIDATION_ERROR",
  ERROR_PARSING_ASSERTION_NOT_ON_OR_AFTER_DATE:
    "ERROR_PARSING_ASSERTION_NOT_ON_OR_AFTER_DATE",
  ERROR_PARSING_ASSERTION_DATE: "ERROR_PARSING_ASSERTION_DATE",
  IN_RESPONSE_TO_FIELD_NOT_FOUND: "IN_RESPONSE_TO_FIELD_NOT_FOUND",
  IN_RESPONSE_TO_EMPTY_OR_INVALID: "IN_RESPONSE_TO_EMPTY_OR_INVALID",
  IN_RESPONSE_TO_ALGORITHM_NOT_VALID: "IN_RESPONSE_TO_ALGORITHM_NOT_VALID",
  INVALID_IN_RESPONSE_TO: "THUMBPRINT_VALIDATION_ERROR",
  IDP_CERT_DATA_NOT_FOUND: "IDP_CERT_DATA_RETRIEVING_ERROR",
  MISSING_ASSERTION_SIGNATURE: "SIGNATURE_VALIDATION_ERROR",
  INVALID_ASSERTION_SIGNATURE: "INVALID_ASSERTION_SIGNATURE",
  ERROR_PARSING_ASSERTION: "ERROR_PARSING_ASSERTION",
  INVALID_SIGNED_HEADER_VALUE: "INVALID_SIGNED_HEADER_VALUE",
};

// HTTP signature verification error codes
const VERIFY_HTTP_ERROR_CODES = {
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  INVALID_SIGNATURE_NUMBER: "INVALID_SIGNATURE_NUMBER",
  INVALID_JWK: "INVALID_JWK",
  UNSUPPORTED_KEY_TYPE: "UNSUPPORTED_KEY_TYPE",
  UNSUPPORTED_ALG: "UNSUPPORTED_ALG",
  INVALID_SIGNATURE_NONCE: "INVALID_SIGNATURE_NONCE",
  INVALID_SIGNATURE_KEY_ID: "INVALID_SIGNATURE_KEY_ID",
  REQUIRED_SIGNED_HEADER_MISSING: "REQUIRED_SIGNED_HEADER_MISSING",
};

module.exports = {
  VALIDATION_ERROR_CODES,
  VERIFY_HTTP_ERROR_CODES,
};
